print("student information")
print("="*50)
id=int(input("enter ur student id:"))
name=input("enter name:")
marks=int(input("enter ur marks:"))
print("="*50)
print("id:{}".format(id))
print("name:{}".format(name))
print("marks:{}".format(marks))
print("="*50)
